---
title: "Analysis"
author: "Lina Elkjær Pedersen"
date: "10/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Libraries}
install.packages("tidyverse")
install.packages("ggplot2")
install.packages("groupdata2")
install.packages("janitor")
install.packages("")
library(tidyverse)
library(ggplot2)
#install.packages("groupdata2")
library(groupdata2) 

#install.packages("janitor")
library(janitor)
library(brms)

#install.packages("lubridate")
library(lubridate)

```



```{r PREPROC_FUNCTION}
#Loading data 
df <- read_csv("DF_BA_test.csv")


df <- df %>% 
  mutate(
    ID = paste(id_in_group, dyad_name),
    gender = as.factor(gender), 
    dyad_name = ifelse(dyad_name == "INESTIMABLE NAVY ROCKHOPPER PENGUIN 96", "UNLIMITED SEPIA MALTESE 98", dyad_name)
  )

demographics_df <- df %>% 
  select(c(dyad_name, gender, GES_score, age, language, parent, experience, regular_contact, position, ID)) %>% 
  unique() %>% 
  mutate(
    response = position, 
    position = NULL
  ) 


#Loading all files to a list
list <- list.files(path = "./Data_sound", pattern = ".csv", all.files = FALSE, full.names = TRUE)


preproc_function <- function(filename) {
  
  #load data
  sounddf <- read_csv(file = filename)
  
    sounddf <- sounddf %>% 
    group_by(stimulus)%>% 
    mutate(
      RT_new = sum(RT),
      startms = time,
      ) %>% 
    filter(RT_new==RT) %>% 
    filter(!(RT==0 & iteration!=4)) %>% 
    arrange(startSequence) %>% 
    ungroup()%>% 
    separate(col="startSequence", into = c("date", "time"), sep=" ") %>% 
    mutate(
      stim_order = 1:8, 
      RT_new = NULL,
      end = NULL,
      start = NULL,
      dyad_name = id,
      volume = NULL, 
      id = NULL,
      date = NULL,
      response = ifelse(response=="Q", "Left", "Right"),
      response = ifelse(RT=="0", "None", response),
      RT_from_onset = ifelse(RT=="0","0", RT-startms),
      stim_category = ifelse(stimulus=="Alarm 1"|
                             stimulus=="Alarm 2"| 
                             stimulus=="Alarm 3"|
                             stimulus=="Alarm 4", "Alarm", "Cry")
    )
  
  dfmerged <- merge(demographics_df, sounddf, by = c("dyad_name","response"), all = TRUE)
  
  dfmerged <- dfmerged %>% 
    separate(col="stimulus", into = c("stim_category", "stim_number"), sep=" ")
  
  return(dfmerged)
}


try <- preproc_function("./Data_sound/v0(1).csv")

df_new = list %>%
    purrr::map_df(preproc_function)


timedf <- try %>% 
  mutate(
    time1 = strptime(time, "%H:%M:%S"))

?as_datetime()


```




```{r BAYESIAN}

get_prior(data = dfmerged, family = binomial(), response ~ 1 + gender:stim_category + (1|ID))


m1_prior <- 
  brm(data=df,
      family = binomial(),
      response ~ 1 + gender:stim_category + (1|ID),
      prior = c(prior(flat),)
      
      

```


```{r}

#Loading data 
df <- read_csv("DF_BA_test.csv")


df <- df %>% 
  mutate(
    ID = paste(id_in_group, dyad_name),
    gender = as.factor(gender), 
    dyad_name = ifelse(dyad_name == "INESTIMABLE NAVY ROCKHOPPER PENGUIN 96", "UNLIMITED SEPIA MALTESE 98", dyad_name)
  )

sounddf<- read_csv("./Data/v0(1).csv")

sounddf <- sounddf %>% 
  group_by(stimulus)%>% 
  mutate(
    RT_new = sum(RT),
    startms = time,
    ) %>% 
  filter(RT_new==RT) %>% 
  filter(!(RT==0 & iteration!=4)) %>% 
  arrange(startSequence) %>% 
  ungroup()%>% 
  separate(col="startSequence", into = c("date", "time"), sep=" ") %>% 
  mutate(
    stim_order = 1:8, 
    RT_new = NULL,
    end = NULL,
    start = NULL,
    dyad_name = id,
    volume = NULL, 
    id = NULL,
    date = NULL,
    response = ifelse(response=="Q", "Left", "Right"),
    response = ifelse(RT=="0", "None", response),
    RT_from_onset = ifelse(RT=="0","0", RT-startms),
    stim_category = ifelse(stimulus=="Alarm 1"|
                           stimulus=="Alarm 2"| 
                           stimulus=="Alarm 3"|
                           stimulus=="Alarm 4", "Alarm", "Cry")  %>% 
  mutate(
    as_datetime(time)   
    ) 



sounddf %>% 
  mutate(
    as_datetime(time))





demographics_df <- df %>% 
  select(c(dyad_name, gender, GES_score, age, language, parent, experience, regular_contact, position, ID)) %>% 
  unique() %>% 
  mutate(
    response = position, 
    position = NULL
  ) 


dfmerged <- merge(demographics_df, sounddf, by = c("dyad_name","response"), all = TRUE)


dfmerged <- dfmerged %>% 
   separate(col="stimulus", into = c("stim_category", "stim_number"), sep=" ")


```


```{r MDOELS FROM SIMULATION}

################################ M2 #################################################  
   
get_prior(data = dfmerged, family = gaussian(), RT ~ 1 + gender + (1| gender) + (1| gender:ID))

m2_gaus_prior <-
  brm(data = dfmerged,
      family = gaussian(),
      RT ~ 1 + gender + (1| gender) + (1| gender:ID),
      prior = c(prior(student_t(3, 11376, 7247), class = Intercept),
                prior(normal(0, 99999), class = b),
                prior(student_t(3, 0, 7247), class = sd),
                prior(student_t(3, 0, 7247), class= sigma)),
      cores=2,
      chains=4,
      sample_prior = "only")

pp_check(m2_gaus_prior, nsamples = 100)+
  ggtitle("M2 Prior Predictive Check")

#################

#WITHOUT "LAST LINE" - 29 divergent transitions. Rhat 1.02. Took 110 seconds
#WITH   "LAST LINE"  -NO divergent transitions. (still says ESS too low) Rhat 1.02. Took 620 sec.
m2_gaus <-
  brm(data = dfmerged,
      family = gaussian(),
      RT ~ 1 + gender + (1| gender)+ (1| gender:ID),
      prior=c(prior(student_t(3, 11376, 7247), class = Intercept),
                prior(normal(0, 99999), class = b),
                prior(student_t(3, 0, 7247), class = sd),
                prior(student_t(3, 0, 7247), class= sigma)),
      cores = 2,
      chains = 4,
      sample_prior = TRUE)


pp_check(m2_gaus, nsamples = 100)+
  ggtitle("M2 Posterior Predictive Check")

summary(m2_gaus)

```





```{r PLOTTING}
# Plotting data:
dfmerged %>% 
  ggplot() +
  aes(x=as.factor(stim_order), y=gender, color=stim_category) +
  geom_point() +
  geom_smooth(method = "lm") +
  theme_classic()

#Where is it coded who pressed the button??? In this plot it looks like we responded every time, but we did not... Maybe it is because we merge by response????

ggplot(data=df, aes(x=time_spent)) + 
      geom_bar(aes(y = ..prop.., fill = success), position = "dodge")+
  facet_wrap(.~id_in_group)+
  theme_linedraw()









```


```{r MODELS}
m1 <- glmer(press ~ gender:sound_type + (1 | ID), dfmerged, family= "binomial")


```



```{r TRYING WinBUGS}
# bugsdir <- "~/Desktop/Bachelor/winbugs14_full_patched/WinBUGS14/" #Set WinBUGS directory, adjust as needed
# 
# k <- 5
# n <- 10
# 
# data <- list("k", "n")
# myinits <- list(
# list(theta = 0.1), #chain 1 starting value
# list(theta = 0.9)) #chain 2 starting value
# 
# parameters <- c("theta")
# 
# samples <- bugs(data, inits=myinits, parameters,
#                 model.file ="Rate_1.txt",
#                 n.chains=2, n.iter=20000, n.burnin=1,n.thin=1,
#                 DIC=T, bugs.directory=bugsdir,
#                codaPkg=F, debug=F)

```

