---
title: "BA_simulations"
author: "Lina Elkjær Pedersen"
date: "11/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Libraries}

library(tidyverse)
library(R2jags)
library(coda)
library(boot)
library(brms)
library(ggplot2)
library(cmdstanr)
#devtools::install_version("retimes","0.1-2")
library(retimes)

set.seed(1997)

```



```{r Structure of data}
## First, we set our data structure

# We have i participants (here 100)
i = 100
# participants have different genders (2)
g = 2
# each participant conducts n trials (8)
n = 8

# Let's now create the baseline data and combine it in a df
# Baseline data doesn't contain the output variable yet
id = rep(c(1:i), each=n) # creates i participants with each n rows
trial = rep(c(1:n), i) # repeat 1 to n trials for i participants
gender = rep(c(0,1), i/g, each=n) # repeat i/2 so that we get half female, half male

# And combine
data <- tibble(id, gender, trial) %>%
    arrange(id, trial)
View(data)
```


```{r rexgauss - Other method for simulation}

# Simulate a population of "good" reaction times:
  # generate an ex-Gaussian population:
  rt_dist1_base_ex <- rexgauss(50, mu=600, sigma=100, 200, positive = F)
  # keep positive values only:
  rt_dist1_base_ex <- rt_dist1_base_ex[rt_dist1_base_ex > 0]

  rt_dist0_base_ex <- rexgauss(50, mu=400, sigma=100, 200, positive = F)
  # keep positive values only:
  rt_dist0_base_ex <- rt_dist0_base_ex[rt_dist0_base_ex > 0]
  
  
  data_ex <- data  %>% 
    mutate(rt_dist = ifelse(gender==0,
                            rep(rt_dist0_base_ex, each = 8),
                            rep(rt_dist1_base_ex, each = 8)),
           RT = rnorm(800, mean=rt_dist, sd=100),
           gender = as.factor(gender))
  
  
  data_ex %>%
    group_by(id) %>%
    ggplot(aes(trial,jitter(RT, factor = .25))) + # a bit of jitter to avoid overplotting
    # one line per id, colored per gender
    geom_line(aes(color=factor(gender),group=id), position = position_dodge(.4)) +
    # Fat line for mean, one per gender
    geom_line(data=summarise(group_by(data_ex, gender, trial), RT = mean(RT)),
                aes(color=factor(gender)), size=2)
  
  
  

```


```{r GAUSSIAN SIMULATION}
# Simulation with different means for gender and individual differences by gender 

  # generate a Gaussian population for gender=1:
  rt_dist1_base <- rnorm(50, mean=6000, sd=2000)
  # keep positive values only:
  rt_dist1_base <- rt_dist1_base[rt_dist1_base > 0]

  #for gender=0:
  rt_dist0_base <- rnorm(50, mean=5000, sd=2000)
  # keep positive values only:
  rt_dist0_base <- rt_dist0_base[rt_dist0_base > 0]
  
  #Generates individual response times based on the gender
  data_gaus <- data  %>%
    mutate(rt_dist = ifelse(gender==0, 
                            rep(rt_dist0_base, each = 8),
                            rep(rt_dist1_base, each = 8)),
           RT = rnorm(800, mean=rt_dist, sd=1000),
           gender = as.factor(gender))
  
  
  data_gaus %>%
    group_by(id) %>%
    ggplot(aes(trial,jitter(RT, factor = .25))) + # a bit of jitter to avoid overplotting
    # one line per id, colored per gender
    geom_line(aes(color=factor(gender),group=id), position = position_dodge(.4)) +
    # Fat line for mean, one per gender
    geom_line(data=summarise(group_by(data_gaus, gender, trial), RT = mean(RT)),
                aes(color=factor(gender)), size=2)
  
  
```




```{r GAUSSIAN MODELS}

get_prior(data = data_gaus, family = gaussian(), RT ~ 1 + gender)
  
  m_gaus_simple_prior <-
  brm(data = data_gaus,
      family = gaussian(),
      RT ~ 1 + gender,
      prior = c(prior(student_t(3, 650, 272), class = Intercept),
                prior(normal(0, 100), class = b),
                prior(student_t(3, 0, 272), class= sigma)),
      chains = 4,
      cores=2,
      sample_prior = "only",
      control = list(adapt_delta = 0.999, max_treedepth = 15))
  
  
 pp_check(m_gaus_simple_prior, nsamples = 100)+
  xlim(0,1000)+
  ggtitle("M_Simple Prior Predictive Check")
 
##################
  m_gaus_simple <-
  brm(data = data_gaus,
      family = gaussian(),
      RT ~ 1 + gender,
      prior = c(prior(student_t(3, 609.1, 233), class = Intercept),
                prior(normal(0, 100), class = b),
                prior(student_t(3, 0, 233), class= sigma)),
      chains = 4,
      cores=2,
      sample_prior = TRUE)
  
  
 pp_check(m_gaus_simple, nsamples = 100)+
  #xlim(0,1000)+
  ggtitle("M_gaus_simple Posterior Predictive Check")
 
 summary(m_gaus_simple)

#################################### M1 ############################################

 get_prior(data = data_gaus, family = gaussian(), RT ~ 1 + gender + (1| id))
 
 
m1_gaus_prior <-
  brm(data = data_gaus,
      family = gaussian(),
      RT ~ 1 + gender + (1| id),
      prior=c(prior(normal(0, 1), class = Intercept),
                prior(normal(0, 1), class = b),
                prior(student_t(3, 0, 233), class = sd),
                prior(student_t(3, 0, 233), class= sigma)),
      cores = 2,
      chains = 4,
      sample_prior = "only")


pp_check(m1_gaus_prior, nsamples = 100)+
  ggtitle("M1 Prior Predictive Check")

  



m1_gaus <-
  brm(data = data_gaus,
      family = gaussian(),
      RT ~ 1 + gender + (1| id),
      prior=c(prior(normal(0, 1), class = Intercept),
                prior(normal(0, 1), class = b),
                prior(student_t(3, 0, 233), class = sd),
                prior(student_t(3, 0, 233), class= sigma)),
      cores = 2,
      chains = 4,
      sample_prior = TRUE)


pp_check(m1_gaus, nsamples = 100)+
  ggtitle("M1 Posterior Predictive Check")

    
################################ M2 #################################################  
  
   
get_prior(data = data_gaus, family = gaussian(), RT ~ 1 + gender + (1| gender) + (1| gender:id))

m2_gaus_prior <-
  brm(data = data_gaus,
      family = gaussian(),
      RT ~ 1 + gender + (1| gender) + (1| gender:id),
      prior =  c(prior(normal(0, 1), class = Intercept),
               prior(normal(0, 1), class = b),
               prior(student_t(3, 0, 2300), class = sd),
              prior(student_t(3, 0, 2300), class= sigma)),
      cores=2,
      chains=4,
      sample_prior = "only")

pp_check(m2_gaus_prior, nsamples = 100)+
  ggtitle("M2 Prior Predictive Check")

#################

#WITHOUT "LAST LINE" - 29 divergent transitions. Rhat 1.02. Took 110 seconds
#WITH   "LAST LINE"  -NO divergent transitions. (still says ESS too low) Rhat 1.02. Took 620 sec.
m2_gaus <-
  brm(data = data_gaus,
      family = gaussian,
      RT ~ 1 + gender + (1| gender)+ (1| gender:id),
      prior=c(prior(student_t(3,618,218), class = Intercept),
                prior(normal(0, 1), class = b),
                prior(student_t(3, 0, 272), class = sd),
                prior(student_t(3, 0, 272), class= sigma)),
      cores = 2,
      chains = 4,
      iter=2000,
      sample_prior = TRUE
      #control = list(adapt_delta = 0.999, max_treedepth = 15)
      )


pp_check(m2_gaus, nsamples = 100)+
  ggtitle("M2 Posterior Predictive Check")
summary(m2_gaus)

?brm





################################ M3 #################################################  
  
   
get_prior(data = data_gaus, family = gaussian(), RT ~ 1 + gender + (1| gender) + (1|id))

m3_gaus_prior <-
  brm(data = data_gaus,
      family = gaussian(),
      RT ~ 1 + gender + (1| gender) + (1|id),
      prior = c(prior(normal(0, 1), class = Intercept),
                prior(normal(0, 1), class = b),
                prior(student_t(3, 0, 233), class = sd),
                prior(student_t(3, 0, 233), class= sigma)),
      cores=2,
      chains=4,
      sample_prior = "only")

pp_check(m3_gaus_prior, nsamples = 100)+
  ggtitle("M3 Prior Predictive Check")

#################

m3_gaus <-
  brm(data = data_gaus,
      family = gaussian(),
      RT ~ 1 + gender + (1| gender) + (1|id),
      prior=c(prior(normal(0, 1), class = Intercept),
                prior(normal(0, 1), class = b),
                prior(student_t(3, 0, 24.6), class = sd),
                prior(student_t(3, 0, 24.6), class= sigma)),
      cores = 2,
      chains = 4,
      sample_prior = TRUE)


pp_check(m3_gaus, nsamples = 100)+
  ggtitle("M3 Posterior Predictive Check")



################################ M4 #################################################  
#M4 should be the one that best explains the data
#Does detect difference between the two means of gender. But expects lower means for both:
#gender0=5037,  gender1=5037-1378=3659      in reality gender0=6000, gender1=5000
#Good at detecting sd and sigma 
   
get_prior(data = data_gaus, family = gaussian(), RT ~ 1 + gender + (1| gender:id))

m4_gaus_prior <-
  brm(data = data_gaus,
      family = gaussian(),
      RT ~ 1 + gender + (1| gender:id),
      prior =  c(prior(student_t(3, 5504, 2375), class = Intercept),
               prior(normal(0, 1000), class = b),
               prior(student_t(3, 0, 2375), class = sd),
               prior(student_t(3, 0, 2375), class= sigma)),
      cores=2,
      chains=4,
      sample_prior = "only")

pp_check(m4_gaus_prior, ndraws = 100)+
  ggtitle("M4 Prior Predictive Check")

#################

m4_gaus <-
  brm(data = data_gaus,
      family = gaussian,
      RT ~ 1 + gender + (1| gender:id),
      prior=c(prior(student_t(3, 5504, 2375), class = Intercept),
                prior(normal(0, 1000), class = b),
                prior(student_t(3, 0, 2375), class = sd),
                prior(student_t(3, 0, 2375), class= sigma)),
      cores = 2,
      chains = 4,
      iter=5000,
      sample_prior = TRUE
      #control = list(adapt_delta = 0.999, max_treedepth = 15)
      )


pp_check(m4_gaus, ndraws = 100)+
  ggtitle("M4 Posterior Predictive Check")
summary(m4_gaus)


################################ M5 #################################################  
  
   
get_prior(data = data_gaus, family = gaussian(), RT ~ 1 + (1| gender) + (1| gender:id))

m5_gaus_prior <-
  brm(data = data_gaus,
      family = gaussian(),
      RT ~ 1 + (1| gender) + (1| gender:id),
      prior =  c(prior(student_t(3, 647.5, 272), class = Intercept),
               prior(student_t(3, 0, 272), class = sd),
              prior(student_t(3, 0, 272), class= sigma)),
      cores=2,
      chains=4,
      sample_prior = "only")

pp_check(m5_gaus_prior, nsamples = 100)+
  ggtitle("M5 Prior Predictive Check")

#################

m5_gaus <-
  brm(data = data_gaus,
      family = gaussian(),
      RT ~ 1 + (1| gender) + (1| gender:id),
      prior=c(prior(student_t(3, 647.5, 272), class = Intercept),
                prior(student_t(3, 0, 272), class = sd),
                prior(student_t(3, 0, 272), class= sigma)),
      cores = 2,
      chains = 4,
      iter=4000,
      sample_prior = TRUE,
      #control = list(adapt_delta = 0.999, max_treedepth = 15)
      )


pp_check(m5_gaus, nsamples = 100)+
  ggtitle("M5 Posterior Predictive Check")
summary(m5_gaus)

```






```{r EXGAUSSIAN MODELS}
get_prior(data = data_ex, family = exgaussian(), RT ~ 1 + gender)
  
  m_simple_prior <-
  brm(data = data_ex,
      family = exgaussian(),
      RT ~ 1 + gender,
      prior = c(prior(student_t(3, 609.1, 233), class = Intercept),
                prior(normal(0, 1), class = b),
                prior(gamma(1, 01), class = beta),
                prior(student_t(3, 0, 233), class= sigma)),
      chains = 4,
      cores=2,
      sample_prior = "only",
      control = list(adapt_delta = 0.999, max_treedepth = 15))
  
  
 pp_check(m_simple_prior, nsamples = 100)+
  xlim(0,1000)+
  ggtitle("M_Simple Prior Predictive Check")
 
##################
   m_simple <-
  brm(data = data_ex,
      family = exgaussian(),
      RT ~ 1 + gender,
      prior = c(prior(student_t(3, 609.1, 233), class = Intercept),
                prior(normal(0, 1), class = b),
                prior(gamma(1, 01), class = beta),
                prior(student_t(3, 0, 233), class= sigma)),
      chains = 4,
      cores=2,
      sample_prior = TRUE)
  
  
 pp_check(m_simple, nsamples = 100)+
  #xlim(0,1000)+
  ggtitle("M_simple Posterior Predictive Check")

#################################### M1 ############################################

 get_prior(data = data_ex, family = exgaussian(), RT ~ 1 + gender + (1| id))
 
 
m1_prior <-
  brm(data = data_ex,
      family = exgaussian(),
      RT ~ 1 + gender + (1| id),
      prior=c(prior(normal(0, 1), class = Intercept),
                prior(normal(0, 1), class = b),
                prior(student_t(3, 0, 233), class = sd),
                prior(gamma(1, 01), class = beta),
                prior(student_t(3, 0, 233), class= sigma)),
      cores = ,
      sample_prior = "only")


pp_check(m1_prior, nsamples = 100)+
  ggtitle("M1 Prior Predictive Check")
summary(m1) 
  



m1 <-
  brm(data = data_ex,
      family = exgaussian(),
      RT ~ 1 + gender + (1| id),
      prior=c(prior(normal(0, 1), class = Intercept),
                prior(normal(0, 1), class = b),
                prior(student_t(3, 0, 233), class = sd),
                prior(gamma(1, 01), class = beta),
                prior(student_t(3, 0, 233), class= sigma)),
      cores = ,
      sample_prior = TRUE)


pp_check(m1, nsamples = 100)+
  ggtitle("M1 Posterior Predictive Check")
summary(m1) 
    
################################ M2 #################################################  
  
   
get_prior(data = data_ex, family = exgaussian(), RT ~ 1 + gender  + (1| gender:id))#+ (1| gender)

m2_prior <-
  brm(data = data_ex,
      family = exgaussian(),
      RT ~ 1 + gender + (1| gender) + (1| gender:id),
      prior = c(prior(normal(0, 1), class = Intercept),
                prior(normal(0, 1), class = b),
                prior(student_t(3, 0, 233), class = sd),
                prior(gamma(1, 01), class = beta),
                prior(student_t(3, 0, 233), class= sigma)),
      cores=2,
      chains=4,
      sample_prior = "only")

pp_check(m2_prior, nsamples = 100)+
  ggtitle("M2 Prior Predictive Check")

#################


m2 <-
  brm(data = data_ex,
      family = exgaussian(),
      RT ~ 1 + gender + (1| gender:id), #+ (1| gender),
      prior=c(prior(student_t(3, 619, 218), class = Intercept),
                prior(normal(1000, 1), class = b),
                prior(student_t(3, 0, 218), class = sd),
                prior(gamma(1, 0.1), class = beta),
                prior(student_t(3, 0, 218), class= sigma)),
      cores = 2,
      chains = 4,
      sample_prior = TRUE)


pp_check(m2, nsamples = 100)+
  ggtitle("M2 Posterior Predictive Check")
summary(m2)


################################ M3 #################################################  
  
   
get_prior(data = data_ex, family = exgaussian(), RT ~ 1 + gender + (1| gender) + (1|id))

m3_prior <-
  brm(data = data_ex,
      family = exgaussian(),
      RT ~ 1 + gender + (1| gender) + (1|id),
      prior = c(prior(normal(0, 1), class = Intercept),
                prior(normal(0, 1), class = b),
                prior(student_t(3, 0, 233), class = sd),
                prior(gamma(1, 01), class = beta),
                prior(student_t(3, 0, 233), class= sigma)),
      cores=2,
      chains=4,
      sample_prior = "only")

pp_check(m3_prior, nsamples = 100)+
  ggtitle("M3 Prior Predictive Check")

#################

m3 <-
  brm(data = data_ex,
      family = exgaussian(),
      RT ~ 1 + gender + (1| gender) + (1|id),
      prior=c(prior(normal(0, 1), class = Intercept),
                prior(normal(0, 1), class = b),
                prior(student_t(3, 0, 24.6), class = sd),
                prior(gamma(1, 01), class = beta),
                prior(student_t(3, 0, 24.6), class= sigma)),
      cores = 2,
      chains = 4,
      sample_prior = TRUE)


pp_check(m3, nsamples = 100)+
  ggtitle("M3 Posterior Predictive Check")

################################ M4 #################################################  
  
   
get_prior(data = data_ex, family = exgaussian(), RT ~ 1 + gender + (1| gender:id))

m4_prior <-
  brm(data = data_ex,
      family = exgaussian(),
      RT ~ 1 + gender + (1| gender:id),
      prior =  c(prior(student_t(3, 670, 218), class = Intercept),
               prior(normal(0, 1000), class = b),
               prior(student_t(3, 0, 218), class = sd),
               prior(student_t(3, 0, 218), class= sigma),
               prior(gamma(1, 0.1), class = beta)), #dont know why this gives an error... It is what it suggests in get_prior...
      cores=2,
      chains=4,
      sample_prior = "only")

pp_check(m4_prior, ndraws = 100)+
  ggtitle("M4 Prior Predictive Check")

#################
#ESS is too low (even for 5000 iterations...)
m4 <-
  brm(data = data_ex,
      family = exgaussian,
      RT ~ 1 + gender + (1| gender:id),
      prior=c(prior(student_t(3, 670, 272), class = Intercept),
                prior(normal(0, 1000), class = b),
                prior(student_t(3, 0, 272), class = sd),
                prior(student_t(3, 0, 272), class= sigma),
                prior(gamma(1, 0.1), class = beta)),
      cores = 2,
      chains = 4,
      iter=5000,
      sample_prior = TRUE,
      #control = list(adapt_delta = 0.999, max_treedepth = 15) #this line doesn't work after updating Stan.... "Fejl i unserialize(socklist[[n]]) : fejl under læsning fra forbindelse" 
      )


pp_check(m4, nsamples = 100)+
  ggtitle("M4 Posterior Predictive Check")
summary(m4)

  
```



```{r}

#Uses different data now, so can't really be compared. 
m4 <- add_criterion(m4, "loo")
m4_gaus <- add_criterion(m4_gaus, "loo")



loo_compare( m4, m4_gaus, criterion = "loo") %>% 
  print(simplify = F)


```








```{r Including a stimulus factor}
# Simulation with different means for gender and individual differences by gender and stimuli_types 

  # generate a Gaussian population for gender=1:
  rt_dist1_base <- rnorm(50, mean=6000, sd=500)
  # keep positive values only:
  rt_dist1_base <- rt_dist1_base[rt_dist1_base > 0]

  #for gender=0:
  rt_dist0_base <- rnorm(50, mean=5000, sd=500)
  # keep positive values only:
  rt_dist0_base <- rt_dist0_base[rt_dist0_base > 0]
  
  stim_female <- rbinom(50, size = 1, prob = 0.7)
  stim_male <- rbinom(50, size = 1, prob = 0.3)
  
  
  data <- tibble(id, gender, trial, stim) %>%
    arrange(id, trial) %>% 
    mutate(
      gender = ifelse(gender ==1, "Male", "Female")
    )
  
  #Generate likelyhood of answering each stim
  stim_dist1_base <- rbinom(400, size = 1, prob = 0.4) #males
  stim_dist0_base <- rbinom(400, size = 1, prob = 0.6) #females
  
  
  #Generates individual response times based on the gender
  data_gaus <- data  %>%
    mutate(rt_dist = ifelse(gender=="Female", 
                            rep(rt_dist0_base, each = 8),
                            rep(rt_dist1_base, each = 8)),
           RT = rnorm(800, mean=rt_dist, sd=1000),
           stim = ifelse(gender=="Female", stim_dist0_base, stim_dist1_base),
           gender = as.factor(gender),
           stim = ifelse (stim==1, "Cry", "Alarm"))
  

  data_gaus %>%
    group_by(id) %>%
    ggplot(aes(trial,stim)) + # a bit of jitter to avoid overplotting
    # one line per id, colored per gender
    geom_point(aes(color=factor(gender),group=id), position = position_dodge(.4)) +
    # Fat line for mean, one per gender
    geom_line(data=summarise(group_by(data_gaus, gender, trial), stim = mean(stim)),
                aes(color=factor(gender)), size=2)
  
  
  
  
```

