---
title: "Pilotdata analysis"
author: "Lina Elkjær Pedersen"
date: "12/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r LIBRARIES}

library(tidyverse)
library(R2jags)
library(coda)
library(boot)
library(brms)
library(ggplot2)
library(bayesplot)
#library(cmdstanr)

#packageVersion("rstan")

```




```{r}

#Loading data
data <- read_csv("dataweek1.csv")

#Getting rid of weird column...
data <-  data %>% 
  mutate(
    ...1 = NULL
  )

data_response <- subset(data, RT!="0")


data_cry <- subset(data, stim_category=="Cries")
```



```{r RT as outcome}
get_prior(data = data_response, family = gaussian(), RT ~ 1 + gender + (1| gender:ID))

m4_gaus_RT_prior <-
  brm(data = data_response,
      family = gaussian(),
      RT~ 1 + gender + (1| gender:ID),
      prior =  c(prior(student_t(3, 5787, 2709), class = Intercept),
               prior(normal(4000, 1000), class = b),
               prior(student_t(3, 0, 2709), class = sd),
               prior(student_t(3, 0, 2709), class= sigma)),
      cores=2,
      chains=4,
      sample_prior = "only")

pp_check(m4_gaus_RT_prior, ndraws = 100)+
  #xlim(-500,500)+
  ggtitle("M4 Prior Predictive Check")

#################

m4_gaus_RT <-
  brm(data = data_response,
      family = gaussian,
      RT ~ 1 + gender + (1| gender:ID),
      prior=c(prior(student_t(3, 5787, 2709), class = Intercept),
                prior(normal(4000, 1000), class = b),
                prior(student_t(3, 0, 2709), class = sd),
                prior(student_t(3, 0, 2709), class= sigma)),
      cores = 2,
      chains = 4,
      iter=5000,
      sample_prior = TRUE
      #control = list(adapt_delta = 0.999, max_treedepth = 15)
      )


pp_check(m4_gaus_RT, ndraws = 100)+
  ggtitle("M4 Posterior Predictive Check")
summary(m4_gaus_RT)

```




```{r RT as outcome + stim}

get_prior(data = data_response, family = gaussian(), RT ~ 0 + gender:stim_category + (1| ID))

m4_gaus_RT_stim_prior <-
  brm(data = data_response,
      family = gaussian(),
      RT~ 0 + gender:stim_category + (1|ID),
      prior =  c(prior(normal(4000, 1000), class = b),
               prior(student_t(3, 0, 2709), class = sd),
               prior(student_t(3, 0, 2709), class= sigma)),
      cores=2,
      chains=4,
      sample_prior = "only")

pp_check(m4_gaus_RT_stim_prior, ndraws = 100)+
  #xlim(-500,500)+
  ggtitle("Response time model - Prior predictive check")

#################

m4_gaus_RT_stim <-
  brm(data = data_response,
      family = gaussian,
      RT ~ 0 + gender:stim_category + (1|ID),
      prior=c(prior(normal(4000, 1000), class = b),
                prior(student_t(3, 0, 2709), class = sd),
                prior(student_t(3, 0, 2709), class= sigma)),
      cores = 2,
      chains = 4,
      iter=5000,
      sample_prior = TRUE
      #control = list(adapt_delta = 0.999, max_treedepth = 15)
      )


pp_check(m4_gaus_RT_stim, ndraws = 100)+
  ggtitle("Response time model - Posterior predictive check")
summary(m4_gaus_RT_stim)

################################################################################################

get_prior(data = data_response, family = gaussian(), RT ~ 0 + gender:stim_category + (1|gender + ID))

m5_gaus_RT_stim_prior <-
  brm(data = data_response,
      family = gaussian(),
      RT~ 0 + gender:stim_category + (1|gender + ID),
      prior =  c(prior(normal(4000, 1000), class = b),
               prior(student_t(3, 0, 2709), class = sd),
               prior(student_t(3, 0, 2709), class= sigma)),
      cores=2,
      chains=4,
      sample_prior = "only")

pp_check(m5_gaus_RT_stim_prior, ndraws = 100)+
  #xlim(-500,500)+
  ggtitle("M4 Prior Predictive Check")

#################

m5_gaus_RT_stim <-
  brm(data = data_response,
      family = gaussian,
      RT ~ 0 + gender:stim_category + (1|gender + ID),
      prior=c(prior(normal(4000, 1000), class = b),
                prior(student_t(3, 0, 2709), class = sd),
                prior(student_t(3, 0, 2709), class= sigma)),
      cores = 2,
      chains = 4,
      iter=5000,
      sample_prior = TRUE
      #control = list(adapt_delta = 0.999, max_treedepth = 15)
      )


pp_check(m5_gaus_RT_stim, ndraws = 100)+
  ggtitle("M4 Posterior Predictive Check")
summary(m5_gaus_RT_stim)

```




NB: Do not understand the output..... It does not clarify which effect it is specific to. 
```{r RT as outcome + stim and GES}

get_prior(data = data_response, family = gaussian(), RT ~ 0 + gender:stim_category:GES_score + (1|ID))

m1_GES_RT_prior <-
  brm(data = data_response,
      family = gaussian(),
      RT~ 0 + gender:stim_category:GES_score + (1|ID),
      prior =  c(prior(normal(4000, 1000), class = b),
               prior(student_t(3, 0, 2709), class = sd),
               prior(student_t(3, 0, 2709), class= sigma)),
      cores=2,
      chains=4,
      sample_prior = "only")

pp_check(m1_GES_RT_prior, ndraws = 100)+
  #xlim(-500,500)+
  ggtitle("M4 Prior Predictive Check")

#################

m1_GES_RT <-
  brm(data = data_response,
      family = gaussian,
      RT ~ 0 + gender:stim_category:GES_score + (1| ID),
      prior=c(prior(normal(4000, 1000), class = b),
                prior(student_t(3, 0, 2709), class = sd),
                prior(student_t(3, 0, 2709), class= sigma)),
      cores = 2,
      chains = 4,
      iter=5000,
      sample_prior = TRUE
      #control = list(adapt_delta = 0.999, max_treedepth = 15)
      )


pp_check(m1_GES_RT, ndraws = 100)+
  ggtitle("M4 Posterior Predictive Check")
summary(m1_GES_RT)




################################### GES MODEL 2 ######################################


get_prior(data = data_response, family = gaussian(), RT ~ 0 + gender:stim_category + GES_score + (1|ID))

m2_GES_RT_prior <-
  brm(data = data_response,
      family = gaussian(),
      RT~ 0 + gender:stim_category + GES_score + (1|ID),
      prior =  c(prior(normal(4000, 1000), class = b),
               prior(student_t(3, 0, 2709), class = sd),
               prior(student_t(3, 0, 2709), class= sigma)),
      cores=2,
      chains=4,
      sample_prior = "only")

pp_check(m2_GES_RT_prior, ndraws = 100)+
  #xlim(-500,500)+
  ggtitle("M4 Prior Predictive Check")

#################

m2_GES_RT <-
  brm(data = data_response,
      family = gaussian,
      RT ~ 0 + gender:stim_category + GES_score + (1| ID),
      prior=c(prior(normal(4000, 1000), class = b),
                prior(student_t(3, 0, 2709), class = sd),
                prior(student_t(3, 0, 2709), class= sigma)),
      cores = 2,
      chains = 4,
      iter=5000,
      sample_prior = TRUE
      #control = list(adapt_delta = 0.999, max_treedepth = 15)
      )


pp_check(m2_GES_RT, ndraws = 100)+
  ggtitle("M4 Posterior Predictive Check")
summary(m2_GES_RT)

```





```{r CREATING A RATE OF ANSWERING PR PARTICIPANT}

data <- data %>% 
  group_by(ID) %>% 
  mutate(
    count_response = ifelse(position==response, 1, 0),
    sum_response = sum(count_response),
    rate = sum_response/8
    
  )

#Okay so I think the mean has to be something other than 0.... Maybe if I remove the data from all participants who never answered. 
#TRY RATE MODELS WITH THIS DATA!!!!
data_rate <- data %>% 
  subset(sum_response!=0)
  )

```




```{r RATE AS OUTCOME}


get_prior(data = data, family = gaussian(), rate ~ 1 + gender + (1| gender:ID))

m4_gaus_rate_prior <-
  brm(data = data,
      family = gaussian(),
      rate ~ 1 + gender + (1| gender:ID),
      prior =  c(prior(student_t(3, 0, 2.5), class = Intercept),
               prior(normal(0, 1000), class = b),
               prior(student_t(3, 0, 2.5), class = sd),
               prior(student_t(3, 0, 2.5), class= sigma)),
      cores=2,
      chains=4,
      sample_prior = "only")

pp_check(m4_gaus_rate_prior, ndraws = 100)+
  #xlim(-500,500)+
  ggtitle("M4 Prior Predictive Check")

#################

m4_gaus_rate <-
  brm(data = data,
      family = gaussian(),
      rate ~ 1 + gender + (1| gender:ID),
      prior=c(prior(student_t(3, 0, 2.5), class = Intercept),
                prior(normal(0, 1000), class = b),
                prior(student_t(3, 0, 2.5), class = sd),
                prior(student_t(3, 0, 2.5), class= sigma)),
      cores = 2,
      chains = 4,
      iter=5000,
      sample_prior = TRUE
      #control = list(adapt_delta = 0.999, max_treedepth = 15)
      )


pp_check(m4_gaus_rate, ndraws = 100)+
  ggtitle("M4 Posterior Predictive Check")
summary(m4_gaus_rate)

################################################### m simple ################################################

get_prior(data = data, family = gaussian(), rate ~ 1 + gender + (1|ID))

m_simple_rate_prior <-
  brm(data = data,
      family = gaussian(),
      rate ~ 1 + gender + (1|ID),
      prior =  c(prior(student_t(3, 0, 2.5), class = Intercept),
               prior(normal(0, 1000), class = b),
               prior(student_t(3, 0, 2.5), class = sd),
               prior(student_t(3, 0, 2.5), class= sigma)),
      cores=2,
      chains=4,
      sample_prior = "only")

pp_check(m_simple_rate_prior, ndraws = 100)+
  #xlim(-500,500)+
  ggtitle("M4 Prior Predictive Check")

#################

m_simple_rate <-
  brm(data = data,
      family = gaussian(),
      rate ~ 1 + gender + (1|ID),
      prior=c(prior(student_t(3, 0, 2.5), class = Intercept),
                prior(normal(0, 1000), class = b),
                prior(student_t(3, 0, 2.5), class = sd),
                prior(student_t(3, 0, 2.5), class= sigma)),
      cores = 2,
      chains = 4,
      iter=5000,
      sample_prior = TRUE
      #control = list(adapt_delta = 0.999, max_treedepth = 15)
      )


pp_check(m_simple_rate, ndraws = 100)+
  ggtitle("M4 Posterior Predictive Check")
summary(m_simple_rate)


```



```{r RATE AS OUTCOME + STIM}

################################### M1 ########################################
get_prior(data = data, family = gaussian(), rate ~ 0 + gender:stim_category + (1| gender:ID))

m1_stim_gaus_rate_prior <-
  brm(data = data,
      family = gaussian(),
      rate ~ 0 + gender:stim_category + (1| gender:ID),
      prior =  c(prior(normal(0, 1000), class = b),
               prior(student_t(3, 0, 2.5), class = sd),
               prior(student_t(3, 0, 2.5), class= sigma)),
      cores=2,
      chains=4,
      sample_prior = "only")

pp_check(m1_stim_gaus_rate_prior, ndraws = 100)+
  #xlim(-500,500)+
  ggtitle("M4 Prior Predictive Check")

#################

m1_stim_gaus_rate <-
  brm(data = data,
      family = gaussian(),
      rate ~ 0 + gender:stim_category + (1| gender:ID),
      prior=c(prior(normal(0, 1000), class = b),
                prior(student_t(3, 0, 2.5), class = sd),
                prior(student_t(3, 0, 2.5), class= sigma)),
      cores = 2,
      chains = 4,
      iter=5000,
      sample_prior = TRUE
      #control = list(adapt_delta = 0.999, max_treedepth = 15)
      )


pp_check(m1_stim_gaus_rate, ndraws = 100)+
  ggtitle("M4 Posterior Predictive Check")
summary(m1_stim_gaus_rate)



################################### M2 ########################################
get_prior(data = data, family = gaussian(), rate ~ 0 + gender:stim_category + (1| ID))

m2_stim_gaus_rate_prior <-
  brm(data = data,
      family = gaussian(),
      rate ~ 0 + gender:stim_category + (1| ID),
      prior =  c(prior(normal(0.5, 0.5), class = b),
               prior(student_t(3, 0, 2.5), class = sd),
               prior(student_t(3, 0, 2.5), class= sigma)),
      cores=2,
      chains=4,
      sample_prior = "only")

pp_check(m2_stim_gaus_rate_prior, ndraws = 100, type = "stat")+
  xlim(0,1)+
  ggtitle("Response rate model - Prior predictive check")

#################

m2_stim_gaus_rate2 <-
  brm(data = data,
      family = gaussian(),
      rate ~ 0 + gender:stim_category + (1|ID),
      prior=c(prior(normal(0.5, 1), class = b),
                prior(student_t(3, 0, 2.5), class = sd),
                prior(student_t(3, 0, 2.5), class= sigma)),
      cores = 2,
      chains = 4,
      iter=5000,
      sample_prior = TRUE
      #control = list(adapt_delta = 0.999, max_treedepth = 15)
      )


pp_check(m2_stim_gaus_rate, ndraws = 100, type = "stat")+
  ggtitle("Response rate model - Posterior predictive check")

summary(m2_stim_gaus_rate1)

#Minder okay meget om de første resultater
summary(m2_stim_gaus_rate)

summary(m2_stim_gaus_rate2)
```





```{r WITH GES}
################################### M2 ########################################

get_prior(data = data, family = gaussian(), rate ~ 0 + gender:stim_category:GES_score + (1| gender:ID))

m3_stim_gaus_rate_prior <-
  brm(data = data,
      family = gaussian(),
      rate ~ 0 + gender:stim_category:GES_score + (1| gender:ID),
      prior =  c(prior(normal(0, 1000), class = b),
               prior(student_t(3, 0, 2.5), class = sd),
               prior(student_t(3, 0, 2.5), class= sigma)),
      cores=2,
      chains=4,
      sample_prior = "only")

pp_check(m3_stim_gaus_rate_prior, ndraws = 100)+
  #xlim(-500,500)+
  ggtitle("M4 Prior Predictive Check")

#################

m3_stim_gaus_rate <-
  brm(data = data,
      family = gaussian(),
      rate ~ 0 + gender:stim_category:GES_score + (1| gender:ID),
      prior=c(prior(normal(0, 1000), class = b),
                prior(student_t(3, 0, 2.5), class = sd),
                prior(student_t(3, 0, 2.5), class= sigma)),
      cores = 2,
      chains = 4,
      iter=5000,
      sample_prior = TRUE
      #control = list(adapt_delta = 0.999, max_treedepth = 15)
      )


pp_check(m3_stim_gaus_rate, ndraws = 100)+
  ggtitle("M4 Posterior Predictive Check")

summary(m3_stim_gaus_rate)

```




```{r DATA = data_cry}

get_prior(data = data_cry, family = gaussian(), rate ~ 0 + gender:GES_score + (1| ID))

m1_cry_prior <-
  brm(data = data_cry,
      family = gaussian(),
      rate ~ 0 + gender:GES_score + (1|ID),
      prior =  c(prior(normal(0.5, 0.5), class = b),
               prior(student_t(3, 0, 2.5), class = sd),
               prior(student_t(3, 0, 2.5), class= sigma)),
      cores=2,
      chains=4,
      sample_prior = "only")

pp_check(m1_cry_prior, ndraws = 100)+
  #xlim(-500,500)+
  ggtitle("M4 Prior Predictive Check")

#################

m1_cry_rate <-
  brm(data = data_cry,
      family = gaussian(),
      rate ~ 0 + gender:GES_score + (1| ID),
      prior=c(prior(normal(0.5, 1), class = b),
                prior(student_t(3, 0, 2.5), class = sd),
                prior(student_t(3, 0, 2.5), class= sigma)),
      cores = 2,
      chains = 4,
      iter=5000,
      sample_prior = TRUE
      #control = list(adapt_delta = 0.999, max_treedepth = 15)
      )


pp_check(m1_cry_rate, ndraws = 100, type = "dens_overlay")+
  ggtitle("M4 Posterior Predictive Check")

summary(m1_cry_rate)

pp_check(m1_cry_rate, ndraws= 100, group = "gender", type = "stat_grouped")

?pp_check
```





```{r}

color_scheme_set("red")

post <- posterior_samples(m4_gaus_RT_stim)

post <- post %>% 
    rename(c( "Estimate: female, alarm" = "b_genderFemale:stim_categoryAlarm",
              "Estimate: male, alarm" = "b_genderMale:stim_categoryAlarm",
              "Estimate: female, cry" = "b_genderFemale:stim_categoryCries",
              "Estimate: male, cry" = "b_genderMale:stim_categoryCries"))
  )

post %>% 
  select(starts_with("Estimate")) %>% 
  mcmc_intervals(prob = .95,
                 point_est = "mean") +
  labs(title = "B) Response time in ms") +
  theme_bw() +
  theme(axis.text.y = element_text(hjust = 0),
        axis.ticks.y = element_blank(),
        panel.grid = element_blank())+
  xlim(0,10000)



summary(m4_gaus_RT_stim)
summary(m2_stim_gaus_rate2)


color_scheme_set("red")

post_rate <- posterior_samples(m2_stim_gaus_rate2)

post_rate <- post_rate %>% 
    rename(c( "Estimate: female, alarm" = "b_genderFemale:stim_categoryAlarm",
              "Estimate: male, alarm" = "b_genderMale:stim_categoryAlarm",
              "Estimate: female, cry" = "b_genderFemale:stim_categoryCries",
              "Estimate: male, cry" = "b_genderMale:stim_categoryCries"))

post_rate %>% 
  select(starts_with("Estimate")) %>% 
  mcmc_intervals(prob = .95,
                 point_est = "mean") +
  labs(title = "A) Response rate") +
  theme_bw() +
  theme(axis.text.y = element_text(hjust = 0),
        axis.ticks.y = element_blank(),
        panel.grid = element_blank())+
  xlim(0,1)
```

