---
title: "Proprocessing 2"
author: "Lina Elkjær Pedersen"
date: "11/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

library(tidyverse)
library(ggplot2)
library(groupdata2) 
library(janitor)
library(brms)
library(lubridate)
library(magrittr)


#read_csv("all_apps_wide_2021-11-29.csv")

#getwd()

#setwd("/Users/linaelkjaerpedersen/Desktop/COBE-Experiment-sync/data")

```


OKAY, so there is a problem with the preproc_function (I moved it to the bottom).... DOING IT MANUALLY BELOW, IT WORKS!

LOADING ALL FILES SEPERATELY AND BINDING THEM

```{r}
#load data
  data_day29 <- read_csv("/Users/linaelkjaerpedersen/Desktop/COBE-Experiment-sync/data/all_apps_wide_2021-11-29.csv")
  data_day30 <- read_csv("/Users/linaelkjaerpedersen/Desktop/COBE-Experiment-sync/data/all_apps_wide_2021-11-30.csv")
  data_day01 <- read_csv("/Users/linaelkjaerpedersen/Desktop/COBE-Experiment-sync/data/all_apps_wide_2021-12-01.csv")
  data_day02 <- read_csv("/Users/linaelkjaerpedersen/Desktop/COBE-Experiment-sync/data/all_apps_wide_2021-12-02.csv")
  data_day03 <- read_csv("/Users/linaelkjaerpedersen/Desktop/COBE-Experiment-sync/data/all_apps_wide_2021-12-03.csv")
  
  #Leaving out day 29 because it is a different length
  data1 <- rbind(data_day30, data_day01, data_day02, data_day03)
  

  
  
  
    #Removing empty columns
  data2 <- data1 %>% remove_empty("cols") 
  data2 <- filter(data2, participant._index_in_pages>2) # Because 2 first matrices are testruns 
  

dfsurvey <- data2 %>% select(matches("survey"))

#################SURVEY#####################
  
  #Changing the long names 
  names(dfsurvey) = gsub(pattern = "survey_followup.1.player.", replacement = "", x = names(dfsurvey))
  
  #Change from wide to long format, around the "q" aka the questions. Data in every other coloumn is repeated
  dfsurvey <- pivot_longer(dfsurvey, cols= starts_with("q"))
  
  dfsurvey$id_in_group <- as.factor(dfsurvey$id_in_group)

  #removing columns where dyad_name is NA
  dfsurvey <- subset(dfsurvey,!is.na(dyad_name))
  
  #Creating individual ID's (id in group + dyad name)
  dfsurvey <- dfsurvey %>% 
  mutate(
    ID = paste(id_in_group, dyad_name),
    gender = as.factor(gender),
    ID = as.factor(ID)
  )
  
  
  #Creating GES_score
  dfsurvey <- dfsurvey %>% 
    #For some reason it only works when the below is done on its own...
    #id_in_group <- as.factor(dfsurvey$id_in_group) %>% 
    group_by(ID) %>% 
    unique() %>% 
    subset(age !="NA") %>% 
    rename(question = name) %>% 
    mutate(
      #Deleting columns
      role = NULL,
      payoff = NULL,
      survey_followup.1.group.id_in_subsession = NULL,
      survey_followup.1.subsession.round_number = NULL,
      GES_score = sum(value/25),
      round = gsub("[q]", "" , question, perl=TRUE),
      round = as.numeric(round),
      )

```



DOING THE EXACT SAME, BUT FOR 29/11, FOR SOME REASON THIS DATA WAS LONGER

```{r DAY29}


data_day29_2 <- data_day29 %>% remove_empty("cols") 
data_day29_2 <- filter(data_day29_2, participant._index_in_pages>2) # Because 2 first matrices are testruns 
  


dfsurvey_day29 <- data_day29_2 %>% select(matches("survey"))

#################SURVEY#####################
  
  #Changing the long names 
  names(dfsurvey_day29) = gsub(pattern = "survey_followup.1.player.", replacement = "", x = names(dfsurvey_day29))
  
  #Change from wide to long format, around the "q" aka the questions. Data in every other coloumn is repeated
  dfsurvey_day29 <- pivot_longer(dfsurvey_day29, cols= starts_with("q"))
  
  dfsurvey_day29$id_in_group <- as.factor(dfsurvey_day29$id_in_group)

  dfsurvey_day29 <- subset(dfsurvey_day29,!is.na(dyad_name))
  
  
  dfsurvey_day29 <- dfsurvey_day29 %>% 
  mutate(
    ID = paste(id_in_group, dyad_name),
    gender = as.factor(gender),
    ID = as.factor(ID)
  )
  
  
  

  
  #Creating GES_score
  dfsurvey_day29 <- dfsurvey_day29 %>% 
    #For some reason it only works when the below is done on its own...
    #id_in_group <- as.factor(dfsurvey$id_in_group) %>% 
    group_by(ID) %>% 
    unique() %>% 
    subset(age !="NA") %>% 
    rename(question = name) %>% 
    mutate(
      #Deleting columns
      role = NULL,
      payoff = NULL,
      survey_followup.1.group.id_in_subsession = NULL,
      survey_followup.1.subsession.round_number = NULL,
      GES_score = sum(value/25),
      round = gsub("[q]", "" , question, perl=TRUE),
      round = as.numeric(round),
      )

  #After the same cleaning process, the day29 looks like the others. I bind them together.

  dfsurvey_full <- rbind(dfsurvey,dfsurvey_day29)
  
# Creating demographics df based on the full survey df
demographics_df <- dfsurvey_full %>% 
  select(c(dyad_name, gender, GES_score, age, language, parent, experience, regular_contact, position, ID, id_in_group)) %>%
  unique() %>% 
  mutate(
    response = position, 
    position = NULL
  )

```




```{r}

#sounddf_old <-read_csv("Data_sound/v0(1).csv")

sounddf<- read_csv("/Users/linaelkjaerpedersen/Desktop/COBE-Experiment-sync/data/MAIN/rt.csv")

sounddf <- sounddf %>% 
  mutate(response = ifelse(response == "Q" | response == "none"| response ==  "Keypad9", response, startSound),
         startSound = ifelse(startSound == "Q" | startSound == "none"| startSound == "Keypad9", volum2 , startSound),
         volume = ifelse(volume==1, volume, volum2/10), 
         ...12 = NULL,
         volum2 = NULL)
    

#NB: Sometimes RT is NA, even though response=Q....


sounddf1 <- sounddf %>%
    group_by(id, stimulus) %>% 
    mutate( 
      RT = as.numeric(RT),
      RT = ifelse(is.na(RT), 1, RT),
      RT_new = sum(RT),
      ) %>% 
    filter(RT_new==RT & RT_new != 0) %>% 
    arrange(startSequence) %>% 
    ungroup()%>% 
    separate(col="startSequence", into = c("date", "time"), sep=" ") %>% 
    mutate(
      #stim_order = 1:8, #does not work since one dyad only has 7.... Because the sound iterations were two close together
      RT = ifelse(RT==1, 0, RT),
      RT_new = NULL,
      end = NULL,
      start = NULL,
      volume = NULL, 
      date = NULL,
      dyad_name = id,
      id = NULL,
      response = ifelse(response=="Q", "Right", response),
      response = ifelse(response=="Keypad9", "Left", response),
      startSound = as.numeric(startSound),
      RT_from_onset = ifelse(RT==0, 0, RT-startSound),
      stim_category = ifelse(stimulus=="Alarm 1"|
                             stimulus=="Alarm 2"| 
                             stimulus=="Alarm 3"|
                             stimulus=="Alarm 4", "Alarm", "Cry")
    )
  
  


dfmerged <- merge(demographics_df, sounddf1, by = c("dyad_name"), all = TRUE)
  
  dfmerged <- dfmerged %>% 
    separate(col="stimulus", into = c("stim_category", "stim_number"), sep=" ") %>% 
    mutate(
      position = response.x, 
     response.x = NULL
    )

rm(data1, data2, data_day01, data_day02, data_day03, data_day29, data_day29_2, data_day30, sounddf, dfsurvey, dfsurvey_day29, dfsurvey_full, demographics_df, sounddf1)
  
  
#Saving data
#write.csv(dfmerged,'dataweek1.csv') 

#Just checking to see how many participants (27, after week one)  
#unique <- as.data.frame(unique(dfmerged$ID))

#Just checking how many responses we have (51/207)
#df_response <- subset(dfmerged, response.y!="none")
```









######################################    PREPROCESSING FUNCTIONS     ############################################





```{r Preprocfunction}

#Loading all files to a list
list <- list.files(path = "/Users/linaelkjaerpedersen/Desktop/COBE-Experiment-sync/data", pattern = ".csv", all.files = FALSE, full.names = TRUE)

#The function
preproc_function <- function(filename) {
  #load data
  data1 <- read_csv(file = filename)
    
  #Removing empty columns
  data2 <- data1 %>% remove_empty("cols") 
  data2 <- filter(data2, participant._index_in_pages>2)
  
    #Splitting into task-specific df's
  dfsurvey <- data1 %>% select(matches("survey"))

  dfmatrix <- data1 %>% select(matches("matrix"))

  dfprisoner <- data1 %>% select(matches("prison"))

  dfpaticipant <- data1 %>% select(matches("participant"))

  dfsession <- data1 %>% select(matches("session"))
  
  
  
  #################SURVEY#####################
  
  #Changing the long names 
  names(dfsurvey) = gsub(pattern = "survey_followup.1.player.", replacement = "", x = names(dfsurvey))
  
  #Change from wide to long format, around the "q" aka the questions. Data in every other coloumn is repeated
  dfsurvey <- pivot_longer(dfsurvey, cols= starts_with("q"))
  
  dfsurvey$id_in_group <- as.factor(dfsurvey$id_in_group)
  
  
  #Creating GES_score
  dfsurvey <- dfsurvey %>% 
    #For some reason it only works when the below is done on its own...
    #id_in_group <- as.factor(dfsurvey$id_in_group) %>% 
    group_by(id_in_group) %>% 
    subset(age !="NA") %>% 
    rename(question = name) %>% 
    mutate(
      #Deleting columns
      role = NULL,
      payoff = NULL,
      survey_followup.1.group.id_in_subsession = NULL,
      survey_followup.1.subsession.round_number = NULL,
      GES_score = sum(value/25),
      round = gsub("[q]", "" , question, perl=TRUE),
      round = as.numeric(round),
      )
  
  
  
    #################PRISONER#####################
  
  #Deleting useless coloums 
  dfprisoner <- subset(dfprisoner, select = !grepl("*group.id_in_subsession", names(dfprisoner)))
  
  #Firstly put everything in the same variable, then separate them. 
  dfprisoner <- dfprisoner %>% 
    mutate_all(as.character) %>% 
    pivot_longer(cols = everything(), names_prefix = "prisoner.", names_to = "variables") %>% 
    separate(variables, into= c("round", "player", "variable"), sep="\\.") %>%
    #deleting useless columns
    subset(player=="player") %>%
    #Splitting the variable-column in three
    mutate(
      id_in_group = ifelse(variable =="id_in_group", value, ""),
      decision = ifelse(variable =="decision", value, ""),
      payoff = ifelse(variable =="payoff", value, ""),
      #Deleting columns
      value = NULL,
      variable= NULL,
      player=NULL,
      #Rearranging values, so the data is in the same rows
      payoff=lead(payoff,2),
      decision= lead(decision,3),
      round = as.numeric(round)
      ) %>%
    #Deleting rows without data
    filter(
      decision!=""
     )
  
  
  #################MATRIX#####################

  
  #Firstly put everything in the same variable, then separate them.
  dfmatrix <- dfmatrix %>%
    mutate_all(as.character) %>%
    pivot_longer(cols = everything(), names_prefix = "matrix_task.", names_to = "variables") %>%
    separate(variables, into= c("round", "player", "variable"), sep="\\.") %>%
    #deleting useless columns
    subset(player=="player") %>%
    subset(value !="NA") %>%
    #Splitting the variable-column in three
    mutate(
      id_in_group = ifelse(variable =="id_in_group", value, ""),
      matrix = ifelse(variable =="matrix", value, ""),
      correct_answer = ifelse(variable =="correct_answer", value, ""),
      answer = ifelse(variable =="answer1", value, ""),
      completed = ifelse(variable =="completed1", value, ""),
      success = ifelse(variable =="success1", value, ""),
      time = ifelse(variable =="time1", value, ""),
      payoff = ifelse(variable =="payoff", value, ""),

      #Deleting columns
      value = NULL,
      variable= NULL,
      player=NULL,
      payoff=NULL,
      #Rearranging values, so the data is in the same rows
      matrix = lead(matrix,2),
      correct_answer = lead(correct_answer,3),
      answer=lead(answer,4),
      completed=lead(completed,5),
      success=lead(success,6),
      time=lead(time,7),
      ) %>%
    #Deleting rows without data
    filter(
      id_in_group!="",
      matrix!="[]")

    dfmatrix$id_in_group <- as.factor(dfmatrix$id_in_group)
    dfmatrix$success <- as.integer(dfmatrix$success)
    dfmatrix$completed <- as.integer(dfmatrix$completed)

    dfmatrix <- dfmatrix %>%
      #For some reason it only works when the below is done on its own...
      #id_in_group <- as.factor(dfmatrix$id_in_group) %>%
      group_by(id_in_group) %>%
      mutate(
        total_success = sum(success),
        total_completed = sum(completed), 
        #Creates variable which contains the time spent on each matrix. 
        #NB The last matrix is NA, however it will not be completed either. 
        time1 = strptime(time, "%H:%M:%S"),
        time_spent = lead(time1)-time1,
        time1=NULL,
        time_spent = gsub("[secs]", "" , time_spent, perl=TRUE), 
        time_spent = as.numeric(time_spent),
        payoff=NULL,
        round = as.numeric(round)
        )
    
    #Merging
    dfmerged<- merge(dfsurvey, dfmatrix, by = c("id_in_group","round"), all = TRUE)
    dfmerged1 <-  merge(dfmerged, dfprisoner, by = c("id_in_group","round"), all = TRUE)

    dfmerged2 <- dfmerged1 %>% 
      group_by(id_in_group) %>% 
      mutate(
        age = age[1],
        gender = gender[1],
        language = language [1], 
        parent = parent[1],
        experience = experience [1], 
        regular_contact=regular_contact[1],
        dyad_name = dyad_name[1],
        position =position[1],
        GES_score=GES_score[1],
        )
  
      return(dfmerged2)
}

#Using the function on the entire list 
df_all_wide = list %>%
  purrr::map_df(preproc_function)

df_all_wide_29 <- preproc_function("/Users/linaelkjaerpedersen/Desktop/COBE-Experiment-sync/data/all_apps_wide_2021-11-29.csv")
df_all_wide_30 <- preproc_function("/Users/linaelkjaerpedersen/Desktop/COBE-Experiment-sync/data/all_apps_wide_2021-11-30.csv")
df_all_wide_01 <- preproc_function("/Users/linaelkjaerpedersen/Desktop/COBE-Experiment-sync/data/all_apps_wide_2021-12-01.csv")
df_all_wide_02 <- preproc_function("/Users/linaelkjaerpedersen/Desktop/COBE-Experiment-sync/data/all_apps_wide_2021-12-02.csv")


df_all_wide_test <- rbind(df_all_wide_29,df_all_wide_30,df_all_wide_01,df_all_wide_02)



```



```{r}
#Loading data 

df_all_wide <- df_all_wide %>% 
  mutate(
    ID = paste(id_in_group, dyad_name),
    gender = as.factor(gender),
    ID = as.factor(ID)
  )

write.csv(df_all_wide_test,'DF_wide_test.csv')

read_csv("DF_wide_test.csv")


#DOES actually does work, but there are only 4 participants.... why?? The data from 30th looks super weird... Also no data from 
demographics_df <- df_all_wide %>% 
  select(c(dyad_name, gender, GES_score, age, language, parent, experience, regular_contact, position, ID, id_in_group)) %>%
  unique() %>% 
  mutate(
    response = position, 
    position = NULL
  )



small <- as.data.frame(df_all_wide$ID) 

small <- unique(small)



kinda_small <- subset(df_all_wide, dyad_name!="NOBLE EBONY OYSTER")

kinda_smaller <- subset(kinda_small, dyad_name!="SAFE BLUE MAGPIE")
  
#Loading all files to a list
#list <- list.files(path = "./Data_sound", pattern = ".csv", all.files = FALSE, full.names = TRUE)


sounddf<- read_csv("/Users/linaelkjaerpedersen/Desktop/COBE-Experiment-sync/data/MAIN/rt.csv")

sound_preproc_function <- function(filename) {
  
  #load data
  sounddf <- read_csv(file = filename)
  
  sounddf <- sounddf %>% 
      mutate(RT = ifelse(is.na(RT), response, RT),
         response = ifelse(response == "Q" | response == "none"| response ==  "Keypad9", response, startSound),
         startSound = ifelse(startSound == "Q" | startSound == "none"| startSound == "Keypad9", volum2 , startSound),
         volume = ifelse(volume==1, volume, volum2/10), 
         ...12 = NULL,
         volum2 = NULL)  %>% 
    group_by(id, stimulus) %>% 
    mutate( 
      RT = as.numeric(RT),
      RT = ifelse(is.na(RT), 1, RT),
      RT_new = sum(RT),
      ) %>% 
    filter(RT_new==RT & RT_new != 0) %>% 
    arrange(startSequence) %>% 
    ungroup()%>% 
    separate(col="startSequence", into = c("date", "time"), sep=" ") %>% 
    mutate(
      #stim_order = 1:8, #does not work since one dyad only has 7.... Because the sound iterations were two close together
      RT = ifelse(RT==1, 0, RT),
      RT_new = NULL,
      end = NULL,
      start = NULL,
      volume = NULL, 
      date = NULL,
      dyad_name = id,
      id = NULL,
      response = ifelse(response=="Q", "Right", response),
      response = ifelse(response=="Keypad9", "Left", response),
      startSound = as.numeric(startSound),
      RT_from_onset = ifelse(RT==0, 0, RT-startSound),
      stim_category = ifelse(stimulus=="Alarm 1"|
                             stimulus=="Alarm 2"| 
                             stimulus=="Alarm 3"|
                             stimulus=="Alarm 4", "Alarm", "Cry")
    )
  
  
  dfmerged <- merge(demographics_df, sounddf, by = c("dyad_name","response"), all = TRUE)
  
  dfmerged <- dfmerged %>% 
    separate(col="stimulus", into = c("stim_category", "stim_number"), sep=" ")
  
  return(dfmerged)
 }


sounddf <- sound_preproc_function("/Users/linaelkjaerpedersen/Desktop/COBE-Experiment-sync/data/MAIN/rt.csv")
df_sound <- sound_preproc_function("/Users/linaelkjaerpedersen/Desktop/COBE-Experiment-sync/data/MAIN/rt.csv")


```


